# -*- coding: utf-8 -*-
"""Assignment_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fb0CFCQ41B9vulxkRbBFVC0au-zVvKQU

Task 1: Create a Dictionary of Student Marks

Problem Statement: Write a Python program that:
1.   Creates a dictionary where student names are keys and their marks are values.
2.   Asks the user to input a student's name.
3.   Retrieves and displays the corresponding marks.
4.   If the student’s name is not found, display an appropriate message.
"""

studentDict ={"Rakesh":99,"Pooja": 35}
userInput = input("Enter the student's name : ")
if (userInput in studentDict):
  print(f"Student: {userInput}'s marks: {studentDict[userInput]}")
else:
  print("Student not found")

"""Task 2: Demonstrate List Slicing
Problem Statement: Write a Python program that:
1.   Creates a list of numbers from 1 to 10.
2.   Extracts the first five elements from the list.
3.   Reverses these extracted elements.
4.   Prints both the extracted list and the reversed list

"""

list1= [i for i in range(1,11)]
list2=list1[:5]
list3=list2[::-1]
print(f"Original list:{list1}")
print(f"Extracted first five elements:{list2}")
print(f"reversed extracted elements:{list3}")